feature: add support for navigation data (127237, 129283, 129284)
SignalK/signalk-to-nmea2000 pull request #54
Opened 2021-04-29 14:52 UTC by ardbiesheuvel

Add support for emitting the various PGNs that carry the information
about the distance and bearing to the active waypoint. This should
provide all information needed by autopilots (heading to steer, XTE)
as well as bearing/distance to waypoint and estimated time of arrival,
which is commonly displayed for human consumption.

Tested with OpenCPN as the producer of APB sentences, and a B&G Triton2
display to show the various data items.

This is based on the outdated and incomplete implementation that lives
on the 'autopilot' branch.

Signed-off-by: Ard Biesheuvel <ardb@kernel.org>

2021-08-08 06:02 UTC, tkurki requested changes
Apologies for the late reply.

Something that I'd like to have added is timeouts for the individual inputs. Timeouts are defined as an array in property named `timeouts`, with the order corresponding to the paths in `keys`. While today all the input data is coming as a single batch from nmea0183 input this may not be so in the future: some input paths may get updated, and some not, and output should be generated based on stale input values.

2021-08-08 06:04 UTC, tkurki reviewed
Also if you rebase on master the pesky test failure for the single unit test we have :-( should go away.

2021-08-08 09:45 UTC, ardbiesheuvel commented
> Apologies for the late reply.
> 
> Something that I'd like to have added is timeouts for the individual inputs. Timeouts are defined as an array in property named `timeouts`, with the order corresponding to the paths in `keys`. While today all the input data is coming as a single batch from nmea0183 input this may not be so in the future: some input paths may get updated, and some not, and output should be generated based on stale input values.

Thanks for the pointers.

I am going to drop the 127237 sentence, by the way. It is currently incorrect, not trivial to implement, and both my Triton2 display as well as my NAC-3 autopilot computer are perfectly happy without it. It seems to me like this is more intended for course computer to display/actuator communication rather than GPS to instruments.

2021-08-08 18:43 UTC, merged

2025-06-28 20:11 UTC, gpenot commented
when I want to parameter NMEA2000 plugin within SignalK, I think that there is an error on "navigation.courseRhumbline.nextPoint.bearingTrue (129284). It as the same PGN 129284 as previous Navigation Data (129284). Should be 129285?

2025-07-08 01:52 UTC, ardbiesheuvel commented
> when I want to parameter NMEA2000 plugin within SignalK, I think that there is an error on "navigation.courseRhumbline.nextPoint.bearingTrue (129284). It as the same PGN 129284 as previous Navigation Data (129284). Should be 129285?

Can you elaborate? Is this an issue related to https://github.com/SignalK/signalk-to-nmea2000/pull/79?

2025-07-08 07:24 UTC, gpenot commented
Yes indeed, and I was wrong, PGN 129285 has nothing to do with it. It is
indeed 129284 that deals with the 2 calculation methods. My apologies and
thank you for your response.

Le mar. 8 juil. 2025 à 03:53, Ard Biesheuvel ***@***.***> a
écrit :

> *ardbiesheuvel* left a comment (SignalK/signalk-to-nmea2000#54)
> <https://github.com/SignalK/signalk-to-nmea2000/pull/54#issuecomment-3047090243>
>
> when I want to parameter NMEA2000 plugin within SignalK, I think that
> there is an error on "navigation.courseRhumbline.nextPoint.bearingTrue
> (129284). It as the same PGN 129284 as previous Navigation Data (129284).
> Should be 129285?
>
> Can you elaborate? Is this an issue related to #79
> <https://github.com/SignalK/signalk-to-nmea2000/pull/79>?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SignalK/signalk-to-nmea2000/pull/54#issuecomment-3047090243>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANP45XBGRPB22BQSLSA3KTL3HMQAJAVCNFSM6AAAAACALJG5PKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTANBXGA4TAMRUGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>